VSPHERE_SERVER: "${vcenter_server}"
VSPHERE_USERNAME: "${vcenter_user}"
VSPHERE_PASSWORD: "${vcenter_password}"
VSPHERE_DATACENTER: "${datacenter}"
VSPHERE_DATASTORE: "${datastore}"
VSPHERE_NETWORK: "${network}"
VSPHERE_RESOURCE_POOL: "${resource_pool}"
VSPHERE_FOLDER: "${vm_folder}"
VSPHERE_TEMPLATE: "${tkg_node_template}"
VSPHERE_HAPROXY_TEMPLATE: "${tkg_haproxy_template}"
VSPHERE_DISK_GIB: 40
VSPHERE_NUM_CPUS: 2
VSPHERE_MEM_MIB: 4096
SERVICE_CIDR: "100.64.0.0/13"
CLUSTER_CIDR: "100.96.0.0/11"
